name: Deploy RAG Model to AWS

# Trigger the workflow on pushes to the main branch
on:
  push:
    branches:
      - main  # You can change this to any branch you prefer (e.g., 'dev')

jobs:
  deploy:
    runs-on: ubuntu-latest  # Defines the runner environment (Ubuntu, macOS, or Windows)

    steps:
    # Step 1: Checkout the repository code
    - name: Checkout repository
      uses: actions/checkout@v2  # This pulls the code from the repository

    # Step 2: Set up Python (if you’re using Python for your RAG model)
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Use a version of Python that you need for your project

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Make sure this file exists in your repository and lists the necessary packages

    # Step 4: Configure AWS credentials using GitHub Secrets
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}  # These are the secrets you'll set up in GitHub
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'us-east-1'  # Replace with your AWS region (e.g., 'us-west-2')

    # Step 5: Deploy RAG model to AWS (e.g., upload model to S3 or deploy to EC2)
    - name: Deploy RAG Model to AWS
      run: |
        aws s3 cp path_to_your_model s3://your-bucket-name/your_model_path  # Example of uploading a model to S3
